FROM openjdk:11

ADD app/target/java-test-app.jar /app/java-test-app.jar

ADD ../../target/debug/libopentelemetry_injector.so /etc/ld.so.preload

ADD ../test/config/otel_config_jvm_agent_not_exists.toml /test/otel_config.toml

ENV OPENTELEMETRY_INJECTOR_CONFIGURATION=/test/otel_config.toml

ENTRYPOINT [ "java", "-jar", "/app/java-test-app.jar" ]