version: '3'
services:

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    networks:
      oteldemomesh:
        aliases: [jaeger]
    ports:
#      - 5775:5775/udp # Accept zipkin.thrift over compact thrift protocol (deprecated, used by legacy clients only)
#      - 6831:6831/udp # Accept jaeger.thrift over compact thrift protocol
#      - 6832:6832/udp # Accept jaeger.thrift over binary thrift protocol
      - 5778:5778 # Serve configs
      - 16686:16686 # Serve frontend
#      - 14268:14268
      - 14250:14250
#      - 9411:9411
#    environment:
#      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

  client:
    build:
      context: ./client
    networks:
      - oteldemomesh
    environment:
      - SERVER_URL=http://server:8081/api/greeting
      - OTEL_RESOURCE_ATTRIBUTES=service.name=client,service.namespace=demo
      - OTEL_TRACES_EXPORTER=jaeger
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14250

  server:
    build:
      context: ./server
    networks:
      oteldemomesh:
        aliases: [server]
    environment:  
      - SERVER_PORT=8081
      - OTEL_RESOURCE_ATTRIBUTES=service.name=server,service.namespace=demo
      - OTEL_TRACES_EXPORTER=jaeger
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14250
    expose:
      - "8081"

networks:
  oteldemomesh: {}