#!/usr/bin/env bash

set -euo pipefail

readonly script_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
readonly project_dir=$(dirname "${script_dir}")

# Build injector base image
(cd "${project_dir}"; docker build . -t opentelemetry-injector:latest)

(cd "${script_dir}"; docker-compose build; docker-compose up)