#!/bin/env bash

set -euo pipefail

readonly script_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
readonly project_dir=$(dirname "${script_dir}")

# Build injector base image
(cd "${project_dir}"; cargo build; docker build . -t otel-injector:latest)

# Create DEB package
(cd "${project_dir}/packaging"; ./build)

# Copy *deb package to the build contexts of the demo containers
cp "${project_dir}"/packaging/*.deb "${script_dir}/client/"
cp "${project_dir}"/packaging/*.deb "${script_dir}/server/"

# Build Java apps
(cd "${script_dir}/client"; ./mvnw package)
(cd "${script_dir}/server"; ./mvnw package)

# TODO Add trap to tear down docker-compose on interrupt
(cd "${script_dir}"; docker-compose build; docker-compose up)