#!/bin/env bash

readonly script_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
readonly project_dir=$(dirname "${script_dir}")

if [ -z "${otel_repo}" ]; then
    otel_repo='https://api.github.com/repos/open-telemetry/opentelemetry-java-instrumentation'
fi

(cp "${project_dir}/target/debug/libopentelemetry_injector.so" "${script_dir}/opentelemetry-injector/opt/opentelemetry/" )
(cd "${script_dir}"; \
    OTEL_JAVA_AGENT_URL=$(curl --silent --fail --show-error "${otel_repo}/releases/latest" | jq -r '.assets[] | select(.name == "opentelemetry-javaagent-all.jar") | .browser_download_url'); \
    echo "Downloading the OpenTelemetry Java agent at: ${OTEL_JAVA_AGENT_URL}"; \
    curl -sL ${OTEL_JAVA_AGENT_URL} -o ./opt/opentelemetry/java/opentelemetry-javaagent-all.jar )

(cd "${script_dir}"; dpkg-deb --build opentelemetry-injector)